site_name: DrawZero — zero boilerplate canvas drawing and animation
site_url: https://drawzero.ru
repo_url: https://github.com/ShashkovS/drawzero

nav:
  - DrawZero: index.md
  - Installation: installation.md
  - Examples Overview: examples_overview.md
  - Examples: examples.md
  - Animations: animation.md
  - Code Reference:
    - Drawing primitives: primitives.md
    - Pt: pt.md
    - Gradient: gradient.md
    - Working with images: images.md
    - Transparency and line width: transparency_and_line_width.md
    - Keyboard and mouse input: keyboard_and_mouse_input.md
    - Architecture: architecture.md
    - Color Table: _color_table.md

theme:
  name: material
  highlightjs: true
  features:
    - navigation.tracking
    - navigation.expand
    - navigation.path
    - toc.follow
    - navigation.top
    - search.suggest
    - search.highlight

plugins:
  - search:
      lang:
        - ru
        - en
  - mkdocstrings:
      default_handler: python
  - i18n:
      docs_structure: suffix
      languages:
        - locale: en
          name: English
          default: true
        - locale: ru
          name: Русский

markdown_extensions:
  - pymdownx.snippets
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.superfences

watch:
  - src
